### ISSUE TITLE
Payment integration with Famoco (Base API)

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-program#96]
- Develop the base API module.
- Create a model for storing API call data for auditing.

Reference: API doc: https://docs.google.com/document/d/1jGVTC4WLons2elJ0RprPSRrN38d_LR84E3kRmnCX6iI/edit

https://github.com/OpenSPP/openspp-api

**How to Use:**

Use any API then check if logs is saved.
To check, navigate to OpenAPI -> OpenAPI -> API Logs

**How to Authenticate to API:**

You need the following:
- Database name
- User Admin's OpenAPI Token - can be found in `Settings -> Users & Companies -> Users -> <Select admin user> -> Allowed APIs -> OpenAPI Token`
- https://www.base64encode.org

Encode OpenAPI Token and database name
- go to https://www.base64encode.org
- in text field, enter this format `<database_name>:<OpenAPI_Token>`
Sample: `odoo15:9b509472-9d98-4b7e-96c2-4558c562dcec`
- click Encode and copy the result
- Add `Authorization` in the Headers of your Request and the value is `Basic <base64encode_value>`.
Sample `"Authorization": "Basic b2RvbzE1MTE6OWI1MDk0NzItOWQ5OC00YjdlLTk2YzItNDU1OGM1NjJkY2Vj"`

**Comment by dasunhegoda** [comment]
The API specification has been completed and sent to @jeremi for review. Awaiting feedback.

**Comment by dasunhegoda** [comment]
@jeremi approved the API spec to release to Famaco for feedback. The implementation will be started today.

**Comment by dasunhegoda** [comment]
@gonzalesedwin1123 will guide @reichie020212 and @emjay0921

**Comment by gonzalesedwin1123** [comment]
@reichie020212 Can you put in the description the authentication requirements and how to authenticate with the API.
